# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: EnterKey PlayGround
subtitle:
author: EnterKey
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://enterkey.github.io/       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: EnterKey Tech Blog
email: enterkey88@gmail.com
description: ""
keyword: "spring spring boot web"
header-img: img/header_img/home-bg-2-dark.png
signature: true #show signature
signature-img: img/signature/BeanTechSign-white.png 


# SNS settings
RSS: true
github_username: enterkey
facebook_username: dooseong.eom
# twitter_username:   Demonbane_x
# linkedin_username:

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: enterkey88

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: UA-133155904-1          # Format: UA-xxxxxx-xx
ga_domain: https://enterkey.github.io


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: img/ironman-draw.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
#- short-about
- category
- recent-posts
- featured-tags
#- friends-blog
- archive

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# nofollow
nofollow:
  enable: true
  exclude:
    - exclude1.com
    - exclude2.com

# robotstxt
robotstxt:
  useragent: "*"
  disallow:
    - /one_file_to_disallow.html
    - /2nd_file_to_disallow.html
    - /3rd_file_to_disallow.html
  allow:
    - /one_file_to_allow.html
    - /2nd_file_to_allow.html
    - /3rd_file_to_allow.html

#feed
feed:
  type: atom
  path: feed.xml
  limit: 20
  hub:


## Friends
#friends: [
#    {
#        title: "Bean Tech",
#        href: "http://beantech.org"
#    },{
#        title: "Kaijun's Blog",
#        href: "http://blog.kaijun.rocks"
#    },{
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    },{
#        title: "It Helps SEO",
#        href: "#"
#    }
#]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/EnterKey/enterkey.github.io.git
  branch: master
